defaults:
  - _self_

input: ???
output: ???
split_file: null
max_examples: null
no_context_placeholder: null

llm:
  _target_: src.client.openai_compatible.LLM
  api_key: ${oc.env:OPENAI_KEY}
  base_url: ${oc.env:OPENAI_URL}
  model: openai/gpt-5-nano
  ensure_nonempty: true
  
qa:
  _target_: src.generation.assembly.MultiAgentQA
  coref_agent:
    _target_: src.agents.coreference.CoreferenceAgent
    llm: ${llm}
  answer_agent:
    _target_: src.agents.answer.AnswerAgent
    llm: ${llm}