"""Agent for answering questions using provided documents."""

from collections.abc import Callable
import copy
from dataclasses import dataclass
from datetime import date
import re

from openai.types.chat import ChatCompletionSystemMessageParam

from src.client.openai_compatible import LLM
from src.shared.prompts import (
    ANSWER_QUESTION,
    DOCUMENT_TEMPLATE,
)
from src.shared.schemas import OPENAI_MESSAGE, OpenAIDocument


class DefaultDocQuestionFormatter:
    def __call__(self, question: str, docs: list[OpenAIDocument]):
        for doc in docs:
            question += DOCUMENT_TEMPLATE.format(content=doc.text)
        return question


def gemini_format_doc(doc_text: str):
    doc_text = doc_text.replace('\r', '')
    doc_text = re.sub(r'\n[\n\s]+', '\n', doc_text).strip()
    doc_text = f'<relevant document start>\n{doc_text}\n<relevant document end>'
    return doc_text


@dataclass
class GeminiDocQuestionFormatter:
    add_rules: bool = True

    def __call__(self, question: str, docs: list[OpenAIDocument]):
        sections: list[str] = [question]  # will be joined by \n\n

        if len(docs):
            sections.append('Answer based on the provided documents:')

        for doc in docs:
            sections.append(gemini_format_doc(doc.text))

        if self.add_rules:
            sections.append(
                'Answer according to the rules:'
                '\n- Cite the document if appropriate, without quotes.'
                '\n- Answer in no more than 7-8 sentences for wide questions, less for factual ones.'
                '\n- Do not write "Based on the provided documents", just assume this.',
            )

        sections.append(
            f'The question again: {question}',
        )

        return '\n\n'.join(sections)


class AnswerAgent:
    """Agent for answering questions."""

    def __init__(
        self,
        llm: LLM,
        sys_prompt: str = ANSWER_QUESTION,
        doc_formatter: Callable[[str, list[OpenAIDocument]], str] | None = None,
    ):
        self.llm = llm
        self.sys_prompt = sys_prompt
        self.doc_formatter = doc_formatter or DefaultDocQuestionFormatter()

    def answer(
        self,
        conversation: list[OPENAI_MESSAGE],
        docs: list[OpenAIDocument],
    ) -> str:
        """Generate the final answer based on the conversation.

        Args:
            conversation: List of messages in the conversation.
            docs: Documents for the last question.

        Returns:
            str: Final answer generated by the model.
        """
        today = date.today().isoformat()

        conversation = copy.deepcopy(conversation)

        assert conversation[-1]['role'] == 'user'
        question = conversation[-1]['content']
        assert isinstance(question, str)

        conversation[-1]['content'] = self.doc_formatter(question, docs)

        system_prompt_text = self.sys_prompt.format(date=today)
        messages: list[OPENAI_MESSAGE] = [
            ChatCompletionSystemMessageParam(role="system", content=system_prompt_text),
            *conversation,
        ]
        return self.llm.generate(messages)
